<?php
if (function_exists('acf_add_local_field_group')):

    acf_add_local_field_group(array(
        'key'                   => 'group_5832e0fd8090f',
        'title'                 => 'Campo Allegato',
        'fields'                => array(
            array(
                'default_value'     => 0,
                'message'           => '',
                'ui'                => 0,
                'ui_on_text'        => '',
                'ui_off_text'       => '',
                'key'               => 'field_5832e11e19786',
                'label'             => __('Document Distributor', 'sage'),
                'name'              => 'documento_distributore',
                'type'              => 'true_false',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
            ),
        ),
        'location'              => array(
            array(
                array(
                    'param'    => 'attachment',
                    'operator' => '==',
                    'value'    => 'all',
                ),
            ),
        ),
        'menu_order'            => 0,
        'position'              => 'normal',
        'style'                 => 'default',
        'label_placement'       => __('top', 'sage'),
        'instruction_placement' => 'label',
        'hide_on_screen'        => '',
        'active'                => 1,
        'description'           => '',
    ));

    acf_add_local_field_group(array(
        'key'                   => 'group_5805d5079ca7e',
        'title'                 => 'Page Title',
        'fields'                => array(
            array(
                'default_value'     => 0,
                'message'           => '',
                'ui'                => 0,
                'ui_on_text'        => '',
                'ui_off_text'       => '',
                'key'               => 'field_5805d51327fa7',
                'label'             => __('Show', 'sage'),
                'name'              => 'show_title',
                'type'              => 'true_false',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
            ),
        ),
        'location'              => array(
            array(
                array(
                    'param'    => 'post_type',
                    'operator' => '==',
                    'value'    => 'page',
                ),
            ),
        ),
        'menu_order'            => 0,
        'position'              => 'normal',
        'style'                 => 'default',
        'label_placement'       => __('top', 'sage'),
        'instruction_placement' => 'label',
        'hide_on_screen'        => '',
        'active'                => 1,
        'description'           => '',
    ));

    acf_add_local_field_group(array(
        'key'                   => 'group_5800c8aaf0be3',
        'title'                 => 'Campi Produttore',
        'fields'                => array(
            array(
                'return_format'     => 'id',
                'preview_size'      => 'thumbnail',
                'library'           => 'all',
                'min_width'         => '',
                'min_height'        => '',
                'min_size'          => '',
                'max_width'         => '',
                'max_height'        => '',
                'max_size'          => '',
                'mime_types'        => '',
                'key'               => 'field_5800c8ca53729',
                'label'             => __('Logo', 'sage'),
                'name'              => 'logo',
                'type'              => 'image',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
            ),
        ),
        'location'              => array(
            array(
                array(
                    'param'    => 'taxonomy',
                    'operator' => '==',
                    'value'    => 'producer',
                ),
            ),
        ),
        'menu_order'            => 0,
        'position'              => 'normal',
        'style'                 => 'default',
        'label_placement'       => __('top', 'sage'),
        'instruction_placement' => 'label',
        'hide_on_screen'        => '',
        'active'                => 1,
        'description'           => '',
    ));

    acf_add_local_field_group(array(
        'key'                   => 'group_57eb94af44525',
        'title'                 => 'Campi Prodotto',
        'fields'                => array(
            array(
                'multiple'          => 0,
                'allow_null'        => 0,
                'choices'           => array(
                    'bevanda' => 'Bevanda',
                    'cibo'    => 'Cibo',
                ),
                'default_value'     => array(
                ),
                'ui'                => 0,
                'ajax'              => 0,
                'placeholder'       => '',
                'return_format'     => 'value',
                'key'               => 'field_582dd4c733f5c',
                'label'             => __('Type', 'sage'),
                'name'              => 'tipo',
                'type'              => 'select',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
            ),
            array(
                'role'              => array(
                    0 => 'producer',
                ),
                'multiple'          => 1,
                'allow_null'        => 0,
                'key'               => 'field_57ebc1698cefa',
                'label'             => __('Producer', 'sage'),
                'name'              => 'produttore',
                'type'              => 'user',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
            ),
            array(
                'return_format'     => 'id',
                'library'           => 'all',
                'min_size'          => '',
                'max_size'          => '',
                'mime_types'        => '',
                'key'               => 'field_5800cfc69276c',
                'label'             => __('Product Details', 'sage'),
                'name'              => 'scheda_prodotto',
                'type'              => 'file',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
            ),
            array(
                'placement'         => 'top',
                'endpoint'          => 0,
                'key'               => 'field_582dd47233f5a',
                'label'             => __('Beverage', 'sage'),
                'name'              => '',
                'type'              => 'tab',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field'    => 'field_582dd4c733f5c',
                            'operator' => '==',
                            'value'    => 'bevanda',
                        ),
                    ),
                ),
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
            ),
            array(
                'default_value'     => '',
                'maxlength'         => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'key'               => 'field_57eb94ee34b40',
                'label'             => __('Name', 'sage'),
                'name'              => 'denominazione',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
            ),
            array(
                'multiple'          => 0,
                'allow_null'        => 1,
                'choices'           => array(
                    'D.O.C.G.' => 'D.O.C.G.',
                    'D.O.C.'   => 'D.O.C.',
                    'I.G.T.'   => 'I.G.T.',
                ),
                'default_value'     => array(
                ),
                'ui'                => 0,
                'ajax'              => 0,
                'placeholder'       => '',
                'return_format'     => 'value',
                'key'               => 'field_57eb950134b41',
                'label'             => __('Classification', 'sage'),
                'name'              => 'classificazione',
                'type'              => 'select',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
            ),
            array(
                'default_value'     => '',
                'maxlength'         => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'key'               => 'field_57eb952634b42',
                'label'             => __('Alcohol Cont. %', 'sage'),
                'name'              => 'alcol',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
            ),
            array(
                'default_value'     => '',
                'maxlength'         => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'key'               => 'field_57eb953634b43',
                'label'             => __('Year', 'sage'),
                'name'              => 'annata',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
            ),
            array(
                'default_value'     => '',
                'new_lines'         => 'wpautop',
                'maxlength'         => '',
                'placeholder'       => '',
                'rows'              => '',
                'key'               => 'field_57eb957634b45',
                'label'             => __('Vinification', 'sage'),
                'name'              => 'vinificazione',
                'type'              => 'textarea',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
            ),
            array(
                'tabs'              => 'all',
                'toolbar'           => 'full',
                'media_upload'      => 1,
                'default_value'     => '',
                'delay'             => 0,
                'key'               => 'field_57eb957b34b46',
                'label'             => __('Organoleptic Characteristics', 'sage'),
                'name'              => 'caratteristiche_organolettiche',
                'type'              => 'wysiwyg',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
            ),
            array(
                'default_value'     => '',
                'new_lines'         => 'wpautop',
                'maxlength'         => '',
                'placeholder'       => '',
                'rows'              => '',
                'key'               => 'field_57eb958134b47',
                'label'             => __('Dining Combinations', 'sage'),
                'name'              => 'abbinamenti',
                'type'              => 'textarea',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
            ),
            array(
                'default_value'     => '',
                'new_lines'         => 'wpautop',
                'maxlength'         => '',
                'placeholder'       => '',
                'rows'              => '',
                'key'               => 'field_57eb958934b48',
                'label'             => __('Temperature for Serving', 'sage'),
                'name'              => 'temperatura_di_servizio',
                'type'              => 'textarea',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
            ),
            array(
                'default_value'     => '',
                'maxlength'         => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'key'               => 'field_5819b64a19270',
                'label'             => __('Annual Production', 'sage'),
                'name'              => 'produzione_annua',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
            ),
            array(
                'default_value'     => '',
                'maxlength'         => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'key'               => 'field_5819b6add3819',
                'label'             => __('Size', 'sage'),
                'name'              => 'formato',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
            ),
            array(
                'placement'         => 'top',
                'endpoint'          => 0,
                'key'               => 'field_582dd4bc33f5b',
                'label'             => __('Food', 'sage'),
                'name'              => '',
                'type'              => 'tab',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field'    => 'field_582dd4c733f5c',
                            'operator' => '==',
                            'value'    => 'cibo',
                        ),
                    ),
                ),
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
            ),
            array(
                'tabs'              => 'all',
                'toolbar'           => 'full',
                'media_upload'      => 1,
                'default_value'     => '',
                'delay'             => 0,
                'key'               => 'field_57eb95ea38219',
                'label'             => __('Product Description', 'sage'),
                'name'              => 'descrizione_prodotto',
                'type'              => 'wysiwyg',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
            ),
            array(
                'default_value'     => '',
                'new_lines'         => 'wpautop',
                'maxlength'         => '',
                'placeholder'       => '',
                'rows'              => '',
                'key'               => 'field_57eb95fa3821a',
                'label'             => __('Allergens', 'sage'),
                'name'              => 'allergeni',
                'type'              => 'textarea',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
            ),
            array(
                'default_value'     => '',
                'new_lines'         => 'wpautop',
                'maxlength'         => '',
                'placeholder'       => '',
                'rows'              => '',
                'key'               => 'field_57eb96033821b',
                'label'             => __('Use and Dining Combination', 'sage'),
                'name'              => 'utilizzo_e_abbinamento',
                'type'              => 'textarea',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
            ),
            array(
                'default_value'     => '',
                'maxlength'         => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'key'               => 'field_57eb96163821c',
                'label'             => __('Origin', 'sage'),
                'name'              => 'provenienza',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
            ),
            array(
                'default_value'     => '',
                'new_lines'         => 'wpautop',
                'maxlength'         => '',
                'placeholder'       => '',
                'rows'              => '',
                'key'               => 'field_57eb961d3821d',
                'label'             => __('Production Process', 'sage'),
                'name'              => 'processo_produttivo',
                'type'              => 'textarea',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
            ),
            array(
                'default_value'     => '',
                'new_lines'         => 'wpautop',
                'maxlength'         => '',
                'placeholder'       => '',
                'rows'              => '',
                'key'               => 'field_57eb96293821e',
                'label'             => __('Notes', 'sage'),
                'name'              => 'note',
                'type'              => 'textarea',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
            ),
        ),
        'location'              => array(
            array(
                array(
                    'param'    => 'post_type',
                    'operator' => '==',
                    'value'    => 'product',
                ),
            ),
        ),
        'menu_order'            => 0,
        'position'              => 'normal',
        'style'                 => 'default',
        'label_placement'       => __('top', 'sage'),
        'instruction_placement' => 'label',
        'hide_on_screen'        => '',
        'active'                => 1,
        'description'           => '',
    ));

endif;
